// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekrdwsmrbeleyhbrjiib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcmR3c21yYmVsZXloYnJqaWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNDA2NjcsImV4cCI6MjA3MTkxNjY2N30.xvQdsJu5I1eCfQXX7DoUUWdAs_GVA6DRyYrufbcxvw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});